### ISSUE TITLE
CI IPv6 testing is unreliable

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-tcp#105]
Currently with the move to Travis CI, testing IPv6 addresses are unreliable.

**Comment by Jorropo** [comment]
@jacobheun I could add a cjdns node in the ci suite, is this a good enough solution for you ?

**Comment by richardschneider** [comment]
FYI: I've never got Travis CI to work IPv6

**Comment by Jorropo** [comment]
I got it to work by playing with sysctl (in sudo mode) and cjdns.
https://travis-ci.org/njh/travis-ipv6-test/jobs/545216549

**Comment by jacobheun** [comment]
@Jorropo would that enable us to run dial and listen tests in the suite? Right now the tests are only doing IPv4. I started work on improving IPv6 support for this but got blocked by the CI situation and then other priorities came up.

We are running a handful of things on Azure right now, and I believe they have better support for IPv6, although I haven't had a chance to test that more in depth yet, so that may be another option here.

**Comment by Jorropo** [comment]
@jacobheun yes, that fully allow test for ipv6 but you can't contact the real ipv6 internet, you have to do on hyperboria (a distributed meshed network) so if you want to conect to external node that only possible if they run cjdroute.

If you only use ::1 that fully works.

**Comment by jacobheun** [comment]
@Jorropo local ipv6 is all we need for this, so that's great, I'm not worried about any external testing for the suite.

**Comment by achingbrain** [comment]
Closing because this repo doesn't use travis for CI any more
