### ISSUE TITLE
[react-native] libp2p-tcp is passing port as string to TCP socket constructor

### ISSUE THREAD

**Issue by kuhnchris** [libp2p/js-libp2p-tcp#108]
Hello,

due to current development and ongoing implementation over at 3box regarding IPFS native running on react-native we found out that whenever we tried to create a libp2p-tcp instance the react-native-tcp android plugin died with an exception regarding java.lang.String cannot be cast to java.lang.Double 

After alot of investigation we found that the solution was to implicit convert the port via ```parseInt(options.port)```. 
Now there are 2 possible solutions: 
- change react-native-tcp to check if the incomming port is a string and convert it
- change libp2p-tcp to provide the port as integer/number instead of string

If you say that libp2p-tcp won't change their behavour then I'll have to try to file a issue against the react-native library. 

Is it cleaner to provide integer or string in this case tho? Maybe this is an extended issue to multiaddr?

Please let me know how you want us to proceed. Manually patching node_modules libraries is no fun. :-(

**Comment by jacobheun** [comment]
We should correct this in js-multiaddr. The return value there is a string, https://github.com/multiformats/js-multiaddr/blob/v6.0.6/src/index.js#L324, but it should be a number to match the nodejs api. Happy to accept a PR for the change there :)

**Comment by kuhnchris** [comment]
Great, then I'll throw it over there and close this one, thanks! :-)
