### ISSUE TITLE
Memory leak in downstream stream-to-it

### ISSUE THREAD

**Issue by betamos** [libp2p/js-libp2p-tcp#127]
Currently, [stream-to-it has a memory leak](https://github.com/alanshaw/stream-to-it/issues/6) in `sink` (and thus `duplex`) resulting in O(n) memory consumption on the sender side. The leak seems seems to live at least for the entire connection, and possibly after the connection is closed as well.

**Comment by jacobheun** [comment]
I will try to look into stream-to-it this week.

**Comment by jacobheun** [comment]
I submitted a fix for the issue in stream-to-it, https://github.com/alanshaw/stream-to-it/pull/7
