### ISSUE TITLE
IPC connections lead to errors after connecting

### ISSUE THREAD

**Issue by robertkiel** [libp2p/js-libp2p-tcp#129]
https://github.com/libp2p/js-libp2p-tcp/blob/562b3adf1f8bccb1328f220bb62cc53ae1d6e10e/src/index.js#L61

`cOpts` will be either a string (in case we are using an IPC connection) or an object (in case we are using a network socket)

Hence, for IPC connections, the following code will fail since `host` and `port` are not defined.

https://github.com/libp2p/js-libp2p-tcp/blob/562b3adf1f8bccb1328f220bb62cc53ae1d6e10e/src/index.js#L66-L76

**Comment by jacobheun** [comment]
Are you seeing actual errors? The logs will definitely be wrong but the code shouldn't be erroring if `cOpts` is a string.

**Comment by lidel** [comment]
Closing due to age, feel free to open new issue if its still a  problem with TS-enabled libp2p.
