### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-tcp#130]
This sometimes happens during CI for js-IPFS, usually after a test has passed and it's tearing down the nodes in an `after` or `afterEach` block.

```
ipfs: [stdout] Error: write EPIPE
ipfs:     at afterWriteDispatched (internal/stream_base_commons.js:154:25)
ipfs:     at writeGeneric (internal/stream_base_commons.js:145:3)
ipfs:     at Socket._writeGeneric (net.js:784:11)
ipfs:     at Socket._write (net.js:796:8)
ipfs:     at doWrite (_stream_writable.js:403:12)
ipfs:     at writeOrBuffer (_stream_writable.js:387:5)
ipfs:     at Socket.Writable.write (_stream_writable.js:318:11)
ipfs:     at /Users/travis/build/ipfs/js-ipfs/node_modules/stream-to-it/sink.js:90:21
ipfs:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ipfs:     at async sink (/Users/travis/build/ipfs/js-ipfs/node_modules/libp2p-tcp/src/socket-to-conn.js:31:9) {
ipfs:   errno: 'EPIPE',
ipfs:   code: 'ERR_UNSUPPORTED_PROTOCOL',
ipfs:   syscall: 'write'
ipfs: }

```

This is with `libp2p-tcp@0.14.5`.

**Comment by jacobheun** [comment]
Is this causing CI to fail when shutting down? The remote end is likely terminating while we're trying to write but we should be catching the error.

**Comment by achingbrain** [comment]
Yes, it causes CI failures.

**Comment by achingbrain** [comment]
Any idea where this should be handled?  I'm seeing this maybe 1 job in 10, and considering each build has 18 jobs that means I see it pretty often.

**Comment by jacobheun** [comment]
Bumping this to a P0 and looking into it as it's currently a huge pain in CI

**Comment by jacobheun** [comment]
Based on the added code it looks like the error is coming from the `newStream` function at https://github.com/libp2p/js-libp2p/blob/v0.27.8/src/upgrader.js#L256. This would indicate that something is calling newStream and during protocol negotiation the socket is closed by the other side. 

This may not be an issue with TCP itself but application/library code not catching errors when calling `dialProtocol` or `connection.newStream`. Looking into where this is being thrown in IPFS.

**Comment by jacobheun** [comment]
@achingbrain I added a patch in js-libp2p@0.28.3 that should help catch errors like this. Can you let me know if you continue to see this in CI after upgrading?

**Comment by dapplion** [comment]
Seeing the same issue recurrently in Lodestar CI and local tests

**Comment by achingbrain** [comment]
I haven't seen this for at least a year so I'm going to close this.  @dapplion please shout if this is still causing problems.
