### ISSUE TITLE
Type error: @libp2p/tcp not compatible with libp2p

### ISSUE THREAD

**Issue by eleijonmarck** [libp2p/js-libp2p-tcp#194]
**What happened:**
I am following the getting started tutorial https://docs.libp2p.io/tutorials/getting-started/javascript/ to step Transports and getting a type error from a minimal example.

**What is expected:**
To be able to run the code without issues. 

Reproduced minimal code example: https://stackblitz.com/edit/node-dsuzra?file=index.ts

```ts
import { createLibp2p } from 'libp2p';
import { TCP } from '@libp2p/tcp';

const main = async () => {
  const tcp = new TCP();
  const node = await createLibp2p({
    transports: [tcp],
  });
};

main();
```

```json
// package.json
{
  "name": "node-starter",
  "version": "0.0.0",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@libp2p/tcp": "^3.0.2",
    "libp2p": "^0.37.3",
    "typescript": "^4.7.4"
  }
}
```

**Comment by mpetrunic** [comment]
This version of @libp2p/tcp is required for new version of libp2p. You can track progress here: https://github.com/libp2p/js-libp2p/pull/1253

With libp2p@0.37.3, please use @libp2p/tcp@1.x
