### ISSUE TITLE
Not working in browsers

### ISSUE THREAD

**Issue by UnsignedInt8** [libp2p/js-libp2p-tcp#88]
As [here](https://libp2p.io/implementations/) described, I was trying to use this module in the browser, but it seems not working.

Here is my code.

![code](https://user-images.githubusercontent.com/15274326/36520846-7b28e74a-17ce-11e8-937f-040a72d44f16.png)

And the result is: 

<img width="1188" alt="screen shot 2018-02-22 at 12 45 15" src="https://user-images.githubusercontent.com/15274326/36520812-4c319342-17ce-11e8-8a8c-6dbf91ef6724.png">

**Comment by dryajov** [comment]
This module is not designed for the browser since the browser lacks TCP support.

**Comment by UnsignedInt8** [comment]
Thanks

**Comment by sunny-g** [comment]
Can [this](https://www.destroyallsoftware.com/sale) be updated? It has this module listed as having browser support.

**Comment by mkg20001** [comment]
@sunny-g I made a pr for that https://github.com/libp2p/website/pull/69
