### ISSUE TITLE
fix example in readme

### ISSUE THREAD

**Issue by soenkehahn** [libp2p/js-libp2p-tcp#89]
I've tried to run the example from the readme, but I get the following error:
```
TypeError: ma.protoNames is not a function
    at EventEmitter.listener.listen ([...]/node_modules/libp2p-tcp/src/listener.js:78:21)
```

I'm guessing that the api changed and the example is out of date. Could this be fixed, please?

Also, maybe there should be examples that are actually checked on CI to prevent these kinds of issues in the future.

**Comment by diasdavid** [comment]
thanks to @drewstone, not it is fixed :)
